/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_client_renderer_Renderer */

#ifndef _Included_xreal_client_renderer_Renderer
#define _Included_xreal_client_renderer_Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_client_renderer_Renderer
 * Method:    setColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_xreal_client_renderer_Renderer_setColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     xreal_client_renderer_Renderer
 * Method:    drawStretchPic
 * Signature: (FFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_xreal_client_renderer_Renderer_drawStretchPic
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     xreal_client_renderer_Renderer
 * Method:    registerFont
 * Signature: (Ljava/lang/String;I)Lxreal/client/renderer/Font;
 */
JNIEXPORT jobject JNICALL Java_xreal_client_renderer_Renderer_registerFont
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     xreal_client_renderer_Renderer
 * Method:    registerMaterial
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xreal_client_renderer_Renderer_registerMaterial
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xreal_client_renderer_Renderer
 * Method:    registerMaterialNoMip
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xreal_client_renderer_Renderer_registerMaterialNoMip
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xreal_client_renderer_Renderer
 * Method:    registerMaterialLightAttenuation
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xreal_client_renderer_Renderer_registerMaterialLightAttenuation
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xreal_client_renderer_Renderer
 * Method:    registerModel
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_xreal_client_renderer_Renderer_registerModel
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     xreal_client_renderer_Renderer
 * Method:    registerAnimation
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xreal_client_renderer_Renderer_registerAnimation
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xreal_client_renderer_Renderer
 * Method:    registerSkin
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xreal_client_renderer_Renderer_registerSkin
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
